# -*- mode: python ; coding: utf-8 -*-
# Kxns Hunter CLI - PyInstaller Spec File

import sys
from pathlib import Path

block_cipher = None

# Get the source directory
src_dir = Path(SPECPATH) / "src"

a = Analysis(
    str(src_dir / "kxns_cli" / "cli" / "__main__.py"),
    pathex=[str(SPECPATH)],
    binaries=[],
    datas=[
        # Include all non-Python files from kxns_cli
        (str(src_dir / "kxns_cli" / "agents"), "kxns_cli/agents"),
        (str(src_dir / "kxns_cli" / "prompts"), "kxns_cli/prompts"),
        (str(src_dir / "kxns_cli" / "skills"), "kxns_cli/skills"),
        (str(src_dir / "kxns_cli" / "tools"), "kxns_cli/tools"),
    ],
    hiddenimports=[
        "kxns_cli",
        "kxns_cli.cli",
        "kxns_cli.app",
        "kxns_cli.config",
        "kxns_cli.llm",
        "kxns_cli.session",
        "kxns_cli.agentspec",
        "kxns_cli.soul",
        "kxns_cli.soul.kxnssoul",
        "kxns_cli.soul.agent",
        "kxns_cli.soul.context",
        "kxns_cli.soul.message",
        "kxns_cli.soul.toolset",
        "kxns_cli.tools",
        "kxns_cli.tools.shell",
        "kxns_cli.tools.file",
        "kxns_cli.tools.web",
        "kxns_cli.tools.multiagent",
        "kxns_cli.tools.ask_user",
        "kxns_cli.tools.todo",
        "kxns_cli.tools.think",
        "kxns_cli.ui",
        "kxns_cli.ui.shell",
        "kxns_cli.ui.print",
        "kxns_cli.wire",
        "kxns_cli.web",
        "kxns_cli.skill",
        "kxns_cli.utils",
        "kosong",
        "kosong.chat_provider",
        "kosong.chat_provider.kimi",
        "pykaos",
        "kaos",
        "kaos.path",
        "prompt_toolkit",
        "rich",
        "typer",
        "loguru",
        "aiohttp",
        "aiofiles",
        "pyyaml",
        "pydantic",
        "fastmcp",
        "httpx",
        "tenacity",
        "fastapi",
        "uvicorn",
        "websockets",
        "jinja2",
        "tomlkit",
        "keyring",
        "setproctitle",
        "ripgrepy",
        "trafilatura",
        "lxml",
        "pillow",
        "streamingjson",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "scipy",
        "pytest",
        "pyright",
        "ruff",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="kxns",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
